
using System;
using System.Runtime.InteropServices;

namespace Selenium
{
    [ComVisible(true)]
    public enum Err
    {
        e0nothing = 0x00,
        e1server = 0x01,
        e2command = 0x02,
        e3assert = 0x04,
        e4verify = 0x08,
    }

    [ComVisible(true)]
    public enum Evt
    {
        e0nothing = 0x00,
        e1errorcmd = 0x01,
        e2assertfailed = 0x02,
        e3verifyfailed = 0x04,
        e4cmdrunned = 0x08,
    }

    [ComVisible(true)]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IEvents
    {
        void DriverEvent(Evt eType, string eMessage);
    }

    [ComVisible(true)]
	public interface IDriver
	{

		Err ErrType{get;}
		string ErrCmd{get;}
		string[] ErrArgs{get;}
		string ErrInfo{get;}
		
		string EvCmd{get;}
		string[] EvArgs{get;}
		
		void setDriverErrorLevel(Err Value);
		void setDriverEventsLevel(Evt Value);

		void start(String serverHost, int serverPort, String browserString, String browserURL);
		void stop();
		string DoCommand(string command, string locator, string value);
		void setExtensionJs(string extensionJs);
		void setAjaxCondition(string condition);
		void addCustomRequestHeader(string key,string value);
		void addLocationStrategy(string strategyName,string functionDefinition);
		void addScript(string scriptContent,string scriptTagId);
		void addSelection(string locator,string optionLocator);
		void allowNativeXpath(string allow);
		void altKeyDown();
		void altKeyDownAndWait();
		void altKeyUp();
		void altKeyUpAndWait();
		void answerOnNextPrompt(string answer);
		void answerOnNextPromptAndWait(string answer);
		void assignId(string locator,string identifier);
		void assignIdAndWait(string locator,string identifier);
		void attachFile(string fieldLocator,string fileLocator);
		void attachFileAndWait(string fieldLocator,string fileLocator);
		void captureEntirePageScreenshot(string filename,string kwargs);
		void captureEntirePageScreenshotAndWait(string filename,string kwargs);
		string captureEntirePageScreenshotToString(string kwargs);
		string captureEntirePageScreenshotToStringAndWait(string kwargs);
		string captureNetworkTraffic(string type);
		string captureNetworkTrafficAndWait(string type);
		void captureScreenshot(string filename);
		void captureScreenshotAndWait(string filename);
		string captureScreenshotToString();
		string captureScreenshotToStringAndWait();
		void check(string locator);
		void checkAndWait(string locator);
		void chooseCancelOnNextConfirmation();
		void chooseCancelOnNextConfirmationAndWait();
		void chooseOkOnNextConfirmation();
		void chooseOkOnNextConfirmationAndWait();
		void click(string locator);
		void clickAndWait(string locator);
		void clickAt(string locator,string coordString);
		void clickAtAndWait(string locator,string coordString);
		void close();
		void closeAndWait();
		void contextMenu(string locator);
		void contextMenuAndWait(string locator);
		void contextMenuAt(string locator,string coordString);
		void contextMenuAtAndWait(string locator,string coordString);
		void controlKeyDown();
		void controlKeyDownAndWait();
		void controlKeyUp();
		void controlKeyUpAndWait();
		void createCookie(string nameValuePair,string optionsString);
		void createCookieAndWait(string nameValuePair,string optionsString);
		void deleteAllVisibleCookies();
		void deleteCookie(string name,string optionsString);
		void deselectPopUp();
		void deselectPopUpAndWait();
		void doubleClick(string locator);
		void doubleClickAndWait(string locator);
		void doubleClickAt(string locator,string coordString);
		void doubleClickAtAndWait(string locator,string coordString);
		void dragAndDrop(string locator,string movementsString);
		void dragAndDropAndWait(string locator,string movementsString);
		void dragAndDropToObject(string locatorOfObjectToBeDragged,string locatorOfDragDestinationObject);
		void dragAndDropToObjectAndWait(string locatorOfObjectToBeDragged,string locatorOfDragDestinationObject);
		void dragdrop(string locator,string movementsString);
		void dragdropAndWait(string locator,string movementsString);
		void fireEvent(string locator,string eventName);
		void fireEventAndWait(string locator,string eventName);
		void focus(string locator);
		void focusAndWait(string locator);
		string getAlert();
		void verifyAlert(string pattern);
		void verifyNotAlert(string pattern);
		void assertAlert(string pattern);
		void assertNotAlert(string pattern);
		void waitForAlert(string pattern);
		void waitForNotAlert(string pattern);
		void storeAlert(string variableName);
		string[] getAllButtons();
		void verifyAllButtons(string pattern);
		void verifyNotAllButtons(string pattern);
		void assertAllButtons(string pattern);
		void assertNotAllButtons(string pattern);
		void waitForAllButtons(string pattern);
		void waitForNotAllButtons(string pattern);
		void storeAllButtons(string variableName);
		string[] getAllFields();
		void verifyAllFields(string pattern);
		void verifyNotAllFields(string pattern);
		void assertAllFields(string pattern);
		void assertNotAllFields(string pattern);
		void waitForAllFields(string pattern);
		void waitForNotAllFields(string pattern);
		void storeAllFields(string variableName);
		string[] getAllLinks();
		void verifyAllLinks(string pattern);
		void verifyNotAllLinks(string pattern);
		void assertAllLinks(string pattern);
		void assertNotAllLinks(string pattern);
		void waitForAllLinks(string pattern);
		void waitForNotAllLinks(string pattern);
		void storeAllLinks(string variableName);
		string[] getAllWindowIds();
		void verifyAllWindowIds(string pattern);
		void verifyNotAllWindowIds(string pattern);
		void assertAllWindowIds(string pattern);
		void assertNotAllWindowIds(string pattern);
		void waitForAllWindowIds(string pattern);
		void waitForNotAllWindowIds(string pattern);
		void storeAllWindowIds(string variableName);
		string[] getAllWindowNames();
		void verifyAllWindowNames(string pattern);
		void verifyNotAllWindowNames(string pattern);
		void assertAllWindowNames(string pattern);
		void assertNotAllWindowNames(string pattern);
		void waitForAllWindowNames(string pattern);
		void waitForNotAllWindowNames(string pattern);
		void storeAllWindowNames(string variableName);
		string[] getAllWindowTitles();
		void verifyAllWindowTitles(string pattern);
		void verifyNotAllWindowTitles(string pattern);
		void assertAllWindowTitles(string pattern);
		void assertNotAllWindowTitles(string pattern);
		void waitForAllWindowTitles(string pattern);
		void waitForNotAllWindowTitles(string pattern);
		void storeAllWindowTitles(string variableName);
		string getAttribute(string attributeLocator);
		void verifyAttribute(string attributeLocator,string pattern);
		void verifyNotAttribute(string attributeLocator,string pattern);
		void assertAttribute(string attributeLocator,string pattern);
		void assertNotAttribute(string attributeLocator,string pattern);
		void waitForAttribute(string attributeLocator,string pattern);
		void waitForNotAttribute(string attributeLocator,string pattern);
		void storeAttribute(string attributeLocator,string variableName);
		string[] getAttributeFromAllWindows(string attributeName);
		void verifyAttributeFromAllWindows(string attributeName,string pattern);
		void verifyNotAttributeFromAllWindows(string attributeName,string pattern);
		void assertAttributeFromAllWindows(string attributeName,string pattern);
		void assertNotAttributeFromAllWindows(string attributeName,string pattern);
		void waitForAttributeFromAllWindows(string attributeName,string pattern);
		void waitForNotAttributeFromAllWindows(string attributeName,string pattern);
		void storeAttributeFromAllWindows(string attributeName,string variableName);
		string getBodyText();
		void verifyBodyText(string pattern);
		void verifyNotBodyText(string pattern);
		void assertBodyText(string pattern);
		void assertNotBodyText(string pattern);
		void waitForBodyText(string pattern);
		void waitForNotBodyText(string pattern);
		void storeBodyText(string variableName);
		string getConfirmation();
		void verifyConfirmation(string pattern);
		void verifyNotConfirmation(string pattern);
		void assertConfirmation(string pattern);
		void assertNotConfirmation(string pattern);
		void waitForConfirmation(string pattern);
		void waitForNotConfirmation(string pattern);
		void storeConfirmation(string variableName);
		string getCookie();
		void verifyCookie(string pattern);
		void verifyNotCookie(string pattern);
		void assertCookie(string pattern);
		void assertNotCookie(string pattern);
		void waitForCookie(string pattern);
		void waitForNotCookie(string pattern);
		void storeCookie(string variableName);
		string getCookieByName(string name);
		void verifyCookieByName(string name,string pattern);
		void verifyNotCookieByName(string name,string pattern);
		void assertCookieByName(string name,string pattern);
		void assertNotCookieByName(string name,string pattern);
		void waitForCookieByName(string name,string pattern);
		void waitForNotCookieByName(string name,string pattern);
		void storeCookieByName(string name,string variableName);
		decimal getCursorPosition(string locator);
		void verifyCursorPosition(string locator,string pattern);
		void verifyNotCursorPosition(string locator,string pattern);
		void assertCursorPosition(string locator,string pattern);
		void assertNotCursorPosition(string locator,string pattern);
		void waitForCursorPosition(string locator,string pattern);
		void waitForNotCursorPosition(string locator,string pattern);
		void storeCursorPosition(string locator,string variableName);
		decimal getElementHeight(string locator);
		void verifyElementHeight(string locator,string pattern);
		void verifyNotElementHeight(string locator,string pattern);
		void assertElementHeight(string locator,string pattern);
		void assertNotElementHeight(string locator,string pattern);
		void waitForElementHeight(string locator,string pattern);
		void waitForNotElementHeight(string locator,string pattern);
		void storeElementHeight(string locator,string variableName);
		decimal getElementIndex(string locator);
		void verifyElementIndex(string locator,string pattern);
		void verifyNotElementIndex(string locator,string pattern);
		void assertElementIndex(string locator,string pattern);
		void assertNotElementIndex(string locator,string pattern);
		void waitForElementIndex(string locator,string pattern);
		void waitForNotElementIndex(string locator,string pattern);
		void storeElementIndex(string locator,string variableName);
		decimal getElementPositionLeft(string locator);
		void verifyElementPositionLeft(string locator,string pattern);
		void verifyNotElementPositionLeft(string locator,string pattern);
		void assertElementPositionLeft(string locator,string pattern);
		void assertNotElementPositionLeft(string locator,string pattern);
		void waitForElementPositionLeft(string locator,string pattern);
		void waitForNotElementPositionLeft(string locator,string pattern);
		void storeElementPositionLeft(string locator,string variableName);
		decimal getElementPositionTop(string locator);
		void verifyElementPositionTop(string locator,string pattern);
		void verifyNotElementPositionTop(string locator,string pattern);
		void assertElementPositionTop(string locator,string pattern);
		void assertNotElementPositionTop(string locator,string pattern);
		void waitForElementPositionTop(string locator,string pattern);
		void waitForNotElementPositionTop(string locator,string pattern);
		void storeElementPositionTop(string locator,string variableName);
		decimal getElementWidth(string locator);
		void verifyElementWidth(string locator,string pattern);
		void verifyNotElementWidth(string locator,string pattern);
		void assertElementWidth(string locator,string pattern);
		void assertNotElementWidth(string locator,string pattern);
		void waitForElementWidth(string locator,string pattern);
		void waitForNotElementWidth(string locator,string pattern);
		void storeElementWidth(string locator,string variableName);
		string getEval(string script);
		void verifyEval(string script,string pattern);
		void verifyNotEval(string script,string pattern);
		void assertEval(string script,string pattern);
		void assertNotEval(string script,string pattern);
		void waitForEval(string script,string pattern);
		void waitForNotEval(string script,string pattern);
		void storeEval(string script,string variableName);
		string getExpression(string expression);
		void verifyExpression(string expression,string pattern);
		void verifyNotExpression(string expression,string pattern);
		void assertExpression(string expression,string pattern);
		void assertNotExpression(string expression,string pattern);
		void waitForExpression(string expression,string pattern);
		void waitForNotExpression(string expression,string pattern);
		void storeExpression(string expression,string variableName);
		string getHtmlSource();
		void verifyHtmlSource(string pattern);
		void verifyNotHtmlSource(string pattern);
		void assertHtmlSource(string pattern);
		void assertNotHtmlSource(string pattern);
		void waitForHtmlSource(string pattern);
		void waitForNotHtmlSource(string pattern);
		void storeHtmlSource(string variableName);
		string getLocation();
		void verifyLocation(string pattern);
		void verifyNotLocation(string pattern);
		void assertLocation(string pattern);
		void assertNotLocation(string pattern);
		void waitForLocation(string pattern);
		void waitForNotLocation(string pattern);
		void storeLocation(string variableName);
		string getLog();
		void verifyLog(string pattern);
		void verifyNotLog(string pattern);
		void assertLog(string pattern);
		void assertNotLog(string pattern);
		void waitForLog(string pattern);
		void waitForNotLog(string pattern);
		void storeLog(string variableName);
		decimal getMouseSpeed();
		void verifyMouseSpeed(string pattern);
		void verifyNotMouseSpeed(string pattern);
		void assertMouseSpeed(string pattern);
		void assertNotMouseSpeed(string pattern);
		void waitForMouseSpeed(string pattern);
		void waitForNotMouseSpeed(string pattern);
		void storeMouseSpeed(string variableName);
		string getPrompt();
		void verifyPrompt(string pattern);
		void verifyNotPrompt(string pattern);
		void assertPrompt(string pattern);
		void assertNotPrompt(string pattern);
		void waitForPrompt(string pattern);
		void waitForNotPrompt(string pattern);
		void storePrompt(string variableName);
		string getSelectedId(string selectLocator);
		void verifySelectedId(string selectLocator,string pattern);
		void verifyNotSelectedId(string selectLocator,string pattern);
		void assertSelectedId(string selectLocator,string pattern);
		void assertNotSelectedId(string selectLocator,string pattern);
		void waitForSelectedId(string selectLocator,string pattern);
		void waitForNotSelectedId(string selectLocator,string pattern);
		void storeSelectedId(string selectLocator,string variableName);
		string[] getSelectedIds(string selectLocator);
		void verifySelectedIds(string selectLocator,string pattern);
		void verifyNotSelectedIds(string selectLocator,string pattern);
		void assertSelectedIds(string selectLocator,string pattern);
		void assertNotSelectedIds(string selectLocator,string pattern);
		void waitForSelectedIds(string selectLocator,string pattern);
		void waitForNotSelectedIds(string selectLocator,string pattern);
		void storeSelectedIds(string selectLocator,string variableName);
		string getSelectedIndex(string selectLocator);
		void verifySelectedIndex(string selectLocator,string pattern);
		void verifyNotSelectedIndex(string selectLocator,string pattern);
		void assertSelectedIndex(string selectLocator,string pattern);
		void assertNotSelectedIndex(string selectLocator,string pattern);
		void waitForSelectedIndex(string selectLocator,string pattern);
		void waitForNotSelectedIndex(string selectLocator,string pattern);
		void storeSelectedIndex(string selectLocator,string variableName);
		string[] getSelectedIndexes(string selectLocator);
		void verifySelectedIndexes(string selectLocator,string pattern);
		void verifyNotSelectedIndexes(string selectLocator,string pattern);
		void assertSelectedIndexes(string selectLocator,string pattern);
		void assertNotSelectedIndexes(string selectLocator,string pattern);
		void waitForSelectedIndexes(string selectLocator,string pattern);
		void waitForNotSelectedIndexes(string selectLocator,string pattern);
		void storeSelectedIndexes(string selectLocator,string variableName);
		string getSelectedLabel(string selectLocator);
		void verifySelectedLabel(string selectLocator,string pattern);
		void verifyNotSelectedLabel(string selectLocator,string pattern);
		void assertSelectedLabel(string selectLocator,string pattern);
		void assertNotSelectedLabel(string selectLocator,string pattern);
		void waitForSelectedLabel(string selectLocator,string pattern);
		void waitForNotSelectedLabel(string selectLocator,string pattern);
		void storeSelectedLabel(string selectLocator,string variableName);
		string[] getSelectedLabels(string selectLocator);
		void verifySelectedLabels(string selectLocator,string pattern);
		void verifyNotSelectedLabels(string selectLocator,string pattern);
		void assertSelectedLabels(string selectLocator,string pattern);
		void assertNotSelectedLabels(string selectLocator,string pattern);
		void waitForSelectedLabels(string selectLocator,string pattern);
		void waitForNotSelectedLabels(string selectLocator,string pattern);
		void storeSelectedLabels(string selectLocator,string variableName);
		string getSelectedValue(string selectLocator);
		void verifySelectedValue(string selectLocator,string pattern);
		void verifyNotSelectedValue(string selectLocator,string pattern);
		void assertSelectedValue(string selectLocator,string pattern);
		void assertNotSelectedValue(string selectLocator,string pattern);
		void waitForSelectedValue(string selectLocator,string pattern);
		void waitForNotSelectedValue(string selectLocator,string pattern);
		void storeSelectedValue(string selectLocator,string variableName);
		string[] getSelectedValues(string selectLocator);
		void verifySelectedValues(string selectLocator,string pattern);
		void verifyNotSelectedValues(string selectLocator,string pattern);
		void assertSelectedValues(string selectLocator,string pattern);
		void assertNotSelectedValues(string selectLocator,string pattern);
		void waitForSelectedValues(string selectLocator,string pattern);
		void waitForNotSelectedValues(string selectLocator,string pattern);
		void storeSelectedValues(string selectLocator,string variableName);
		string[] getSelectOptions(string selectLocator);
		void verifySelectOptions(string selectLocator,string pattern);
		void verifyNotSelectOptions(string selectLocator,string pattern);
		void assertSelectOptions(string selectLocator,string pattern);
		void assertNotSelectOptions(string selectLocator,string pattern);
		void waitForSelectOptions(string selectLocator,string pattern);
		void waitForNotSelectOptions(string selectLocator,string pattern);
		void storeSelectOptions(string selectLocator,string variableName);
		string getSpeed();
		void verifySpeed(string pattern);
		void verifyNotSpeed(string pattern);
		void assertSpeed(string pattern);
		void assertNotSpeed(string pattern);
		void waitForSpeed(string pattern);
		void waitForNotSpeed(string pattern);
		void storeSpeed(string variableName);
		string getTable(string tableCellAddress);
		void verifyTable(string tableCellAddress,string pattern);
		void verifyNotTable(string tableCellAddress,string pattern);
		void assertTable(string tableCellAddress,string pattern);
		void assertNotTable(string tableCellAddress,string pattern);
		void waitForTable(string tableCellAddress,string pattern);
		void waitForNotTable(string tableCellAddress,string pattern);
		void storeTable(string tableCellAddress,string variableName);
		string getText(string locator);
		void verifyText(string locator,string pattern);
		void verifyNotText(string locator,string pattern);
		void assertText(string locator,string pattern);
		void assertNotText(string locator,string pattern);
		void waitForText(string locator,string pattern);
		void waitForNotText(string locator,string pattern);
		void storeText(string locator,string variableName);
		string getTitle();
		void verifyTitle(string pattern);
		void verifyNotTitle(string pattern);
		void assertTitle(string pattern);
		void assertNotTitle(string pattern);
		void waitForTitle(string pattern);
		void waitForNotTitle(string pattern);
		void storeTitle(string variableName);
		string getValue(string locator);
		void verifyValue(string locator,string pattern);
		void verifyNotValue(string locator,string pattern);
		void assertValue(string locator,string pattern);
		void assertNotValue(string locator,string pattern);
		void waitForValue(string locator,string pattern);
		void waitForNotValue(string locator,string pattern);
		void storeValue(string locator,string variableName);
		bool getWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void verifyWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void verifyNotWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void assertWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void assertNotWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void waitForWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void waitForNotWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		void storeWhetherThisFrameMatchFrameExpression(string currentFrameString,string target);
		bool getWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void verifyWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void verifyNotWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void assertWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void assertNotWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void waitForWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void waitForNotWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		void storeWhetherThisWindowMatchWindowExpression(string currentWindowString,string target);
		decimal getXpathCount(string xpath);
		void verifyXpathCount(string xpath,string pattern);
		void verifyNotXpathCount(string xpath,string pattern);
		void assertXpathCount(string xpath,string pattern);
		void assertNotXpathCount(string xpath,string pattern);
		void waitForXpathCount(string xpath,string pattern);
		void waitForNotXpathCount(string xpath,string pattern);
		void storeXpathCount(string xpath,string variableName);
		decimal GetCSSCount(string cssLocator);
		void goBack();
		void goBackAndWait();
		void highlight(string locator);
		void highlightAndWait(string locator);
		void ignoreAttributesWithoutValue(string ignore);
		void ignoreAttributesWithoutValueAndWait(string ignore);
		bool isAlertPresent();
		void verifyAlertPresent();
		void verifyAlertNotPresent();
		void assertAlertPresent();
		void assertAlertNotPresent();
		void storeAlertPresent(string variableName);
		void waitForAlertPresent();
		void waitForNotAlertPresent();
		bool isChecked(string locator);
		void verifyChecked(string locator);
		void verifyNotChecked(string locator);
		void assertChecked(string locator);
		void assertNotChecked(string locator);
		void storeChecked(string locator,string variableName);
		void waitForChecked(string locator);
		void waitForNotChecked(string locator);
		bool isConfirmationPresent();
		void verifyConfirmationPresent();
		void verifyConfirmationNotPresent();
		void assertConfirmationPresent();
		void assertConfirmationNotPresent();
		void storeConfirmationPresent(string variableName);
		void waitForConfirmationPresent();
		void waitForNotConfirmationPresent();
		bool isCookiePresent(string name);
		void verifyCookiePresent(string name);
		void verifyNotCookiePresent(string name);
		void assertCookiePresent(string name);
		void assertNotCookiePresent(string name);
		void storeCookiePresent(string name,string variableName);
		void waitForCookiePresent(string name);
		void waitForNotCookiePresent(string name);
		bool isEditable(string locator);
		void verifyEditable(string locator);
		void verifyNotEditable(string locator);
		void assertEditable(string locator);
		void assertNotEditable(string locator);
		void storeEditable(string locator,string variableName);
		void waitForEditable(string locator);
		void waitForNotEditable(string locator);
		bool isElementPresent(string locator);
		void verifyElementPresent(string locator);
		void verifyElementNotPresent(string locator);
		void assertElementPresent(string locator);
		void assertElementNotPresent(string locator);
		void storeElementPresent(string locator,string variableName);
		void waitForElementPresent(string locator);
		void waitForNotElementPresent(string locator);
		bool isOrdered(string locator1,string locator2);
		void verifyOrdered(string locator1,string locator2);
		void verifyNotOrdered(string locator1,string locator2);
		void assertOrdered(string locator1,string locator2);
		void assertNotOrdered(string locator1,string locator2);
		void storeOrdered(string locator1,string locator2);
		void waitForOrdered(string locator1,string locator2);
		void waitForNotOrdered(string locator1,string locator2);
		bool isPromptPresent();
		void verifyPromptPresent();
		void verifyNotPromptPresent();
		void assertPromptPresent();
		void assertNotPromptPresent();
		void storePromptPresent(string variableName);
		void waitForPromptPresent();
		void waitForNotPromptPresent();
		bool isSomethingSelected(string selectLocator);
		void verifySomethingSelected(string selectLocator);
		void verifyNotSomethingSelected(string selectLocator);
		void assertSomethingSelected(string selectLocator);
		void assertNotSomethingSelected(string selectLocator);
		void storeSomethingSelected(string selectLocator,string variableName);
		void waitForSomethingSelected(string selectLocator);
		void waitForNotSomethingSelected(string selectLocator);
		bool isTextPresent(string pattern);
		void verifyTextPresent(string pattern);
		void verifyTextNotPresent(string pattern);
		void assertTextPresent(string pattern);
		void assertTextNotPresent(string pattern);
		void storeTextPresent(string pattern,string variableName);
		void waitForTextPresent(string pattern);
		void waitForTextNotPresent(string pattern);
		bool isVisible(string locator);
		void verifyVisible(string locator);
		void verifyNotVisible(string locator);
		void assertVisible(string locator);
		void assertNotVisible(string locator);
		void storeVisible(string locator,string variableName);
		void waitForVisible(string locator);
		void waitForNotVisible(string locator);
		void keyDown(string locator,string keySequence);
		void keyDownAndWait(string locator,string keySequence);
		void keyDownNative(string keycode);
		void keyDownNativeAndWait(string keycode);
		void keyPress(string locator,string keySequence);
		void keyPressAndWait(string locator,string keySequence);
		void keyPressNative(string keycode);
		void keyPressNativeAndWait(string keycode);
		void keyUp(string locator,string keySequence);
		void keyUpAndWait(string locator,string keySequence);
		void keyUpNative(string keycode);
		void keyUpNativeAndWait(string keycode);
		void metaKeyDown();
		void metaKeyDownAndWait();
		void metaKeyUp();
		void metaKeyUpAndWait();
		void mouseDown(string locator);
		void mouseDownAndWait(string locator);
		void mouseDownAt(string locator,string coordString);
		void mouseDownAtAndWait(string locator,string coordString);
		void mouseDownRight(string locator);
		void mouseDownRightAndWait(string locator);
		void mouseDownRightAt(string locator,string coordString);
		void mouseDownRightAtAndWait(string locator,string coordString);
		void mouseMove(string locator);
		void mouseMoveAndWait(string locator);
		void mouseMoveAt(string locator,string coordString);
		void mouseMoveAtAndWait(string locator,string coordString);
		void mouseOut(string locator);
		void mouseOutAndWait(string locator);
		void mouseOver(string locator);
		void mouseOverAndWait(string locator);
		void mouseUp(string locator);
		void mouseUpAndWait(string locator);
		void mouseUpAt(string locator,string coordString);
		void mouseUpAtAndWait(string locator,string coordString);
		void mouseUpRight(string locator);
		void mouseUpRightAndWait(string locator);
		void mouseUpRightAt(string locator,string coordString);
		void mouseUpRightAtAndWait(string locator,string coordString);
		void open(string url);
		void openAndWait(string url);
		void open(string url,string ignoreResponseCode);
		void openAndWait(string url,string ignoreResponseCode);
		void openWindow(string url,string windowID);
		void openWindowAndWait(string url,string windowID);
		void refresh();
		void refreshAndWait();
		void removeAllSelections(string locator);
		void removeAllSelectionsAndWait(string locator);
		void removeScript(string scriptTagId);
		void removeScriptAndWait(string scriptTagId);
		void removeSelection(string locator,string optionLocator);
		void removeSelectionAndWait(string locator,string optionLocator);
		string retrieveLastRemoteControlLogs();
		void rollup(string rollupName,string kwargs);
		void rollupAndWait(string rollupName,string kwargs);
		void runScript(string script);
		void runScriptAndWait(string script);
		void select(string selectLocator,string optionLocator);
		void selectAndWait(string selectLocator,string optionLocator);
		void selectFrame(string locator);
		void selectFrameAndWait(string locator);
		void selectPopUp(string windowID);
		void selectPopUpAndWait(string windowID);
		void selectWindow(string windowID);
		void selectWindowAndWait(string windowID);
		void setBrowserLogLevel(string logLevel);
		void setContext(string context);
		void setCursorPosition(string locator,string position);
		void setMouseSpeed(string pixels);
		void setSpeed(string value);
		void setTimeout(string timeout);
		void shiftKeyDown();
		void shiftKeyDownAndWait();
		void shiftKeyUp();
		void shiftKeyUpAndWait();
		void showContextualBanner();
		void showContextualBannerAndWait();
		void showContextualBanner(string className,string methodName);
		void showContextualBannerAndWait(string className,string methodName);
		void shutDownSeleniumServer();
		void shutDownSeleniumServerAndWait();
		void submit(string formLocator);
		void submitAndWait(string formLocator);
		void type(string locator,string value);
		void typeAndWait(string locator,string value);
		void typeKeys(string locator,string value);
		void typeKeysAndWait(string locator,string value);
		void uncheck(string locator);
		void uncheckAndWait(string locator);
		void useXpathLibrary(string libraryName);
		void waitForCondition(string script,string timeout);
		void waitForFrameToLoad(string frameAddress,string timeout);
		void waitForPageToLoad(string timeout);
		void waitForPopUp(string windowID,string timeout);
		void windowFocus();
		void windowFocusAndWait();
		void windowMaximize();
		void windowMaximizeAndWait();
		string[] getXpathAttribute(string xpath);
		void verifyXpathAttribute(string xpath,string pattern);
		void verifyNotXpathAttribute(string xpath,string pattern);
		void assertXpathAttribute(string xpath,string pattern);
		void assertNotXpathAttribute(string xpath,string pattern);
		void waitForXpathAttribute(string xpath,string pattern);
		void waitForNotXpathAttribute(string xpath,string pattern);
		void storeXpathAttribute(string xpath,string variableName);
		string[] getXpathValue(string xpath);
		void verifyXpathValue(string xpath,string pattern);
		void verifyNotXpathValue(string xpath,string pattern);
		void assertXpathValue(string xpath,string pattern);
		void assertNotXpathValue(string xpath,string pattern);
		void waitForXpathValue(string xpath,string pattern);
		void waitForNotXpathValue(string xpath,string pattern);
		void storeXpathValue(string xpath,string variableName);
		void pause(string waitTime);
		void pauseAndWait(string waitTime);

	}
}